rochefort-lab/fissa

README.md
Making this change because Shippable doesn't support Python 3.7,
whereas Travis does, so I would rather test on Travis over
Shippable. Since I will soon be adding Python 3.7 to the CI build
list, Shippable will start failing and so I want the badge to
swap to Travis before that happens.
=> DOC: Change build status badge Shippable->Travis

fissa/deltaf.py
Can't filter at 1Hz for signals with fs < 2Hz!
Instead, we now
- low-pass filter at 1Hz for fs > 2Hz
- low-pass filter at Nyquist rate for frequencies  1Hz < fs < 2Hz
- don't filter for fs < 1 Hz
Closes #25.
=> BUG: Fix f0 detection with low sampling rates

CHANGELOG.md
I initialised the CHANGELOG using this tool:
https://github.com/github-changelog-generator/github-changelog-generator
Command
```
github_changelog_generator -u rochefort-lab -p fissa
```
And then I refactored it to so the PRs it listed were organised following the style guide of [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
=> DOC: Add CHANGELOG, from 0.5.0 to 0.5.2dev (current)

CONTRIBUTING.md, fissa/core.py, fissa/datahandler.py, fissa/datahandler_framebyframe.py, fissa/deltaf.py, fissa/neuropil.py, fissa/roitools.py
Tidy up all the docstrings. Fix some entries which were mistaken, add some missing returns, otherwise clarify text or change to match numpy documentation styleguide recommendations.
=> DOC: fix docstrings

fissa/__meta__.py
In previous commit 83dd012, PR #37, the version number was accidentally decremented when changing the location in which version numbers are housed.
=> MAINT: Fix accidental version change

examples/Basic usage.html, examples/Basic usage.ipynb, examples/basic_usage_windows.py
This adds an extra basic example Python script for Windows users, as multiprocessing expects an explicit ```if __name__ == '__main__':``` statement around the main code being run, but only for Windows. This fixes issue #24.
=> Windows example script

docs/conf.py, fissa/__meta__.py, setup.py
During install step, we can't import `__meta__.py` directly because
it loads `__init__.py` first, and that means importing other things
which aren't installed.
To escape this cycle, we use solution 3 shown here:
https://packaging.python.org/guides/single-sourcing-package-version/
which is to `exec()` the file contents of `__meta__.py` instead of
import them.
=> BUG: Workaround for setup.py install accessing __meta__.py

setup.py
Should now be able to install the documentation requirements through setup.py and hence (on next release) pip.
=> MAINT: Add docs requirements to setup.py

fissa/__init__.py
We now import __meta__ into fissa's __init__.py, instead of importing the contents of __meta__ with `import *`.
Also, make the version number available as `fissa.__version__` again, by aliasing `fissa.__meta__.version`.
=> MAINT: __init__ import __meta__ directly

fissa/__meta__.py
This conforms with our new standard for the master branch version number, conforming to [PEP440](https://www.python.org/dev/peps/pep-0440).
=> REL: Update master version number to 0.6.dev0

CHANGELOG.rst
Changes the formatting of the changelog, aiming to make it easier to read.
- Add "Version" to title of entries
- Date no longer in title, instead on separate line
- Full changelog link text clearer
- Don't include author of PR (its not necessary information for the reader to know this)
=> DOC: Reformat Changelog

fissa/core.py
Fixed:
-   Use `ncores_preparation` for perparation step, not `ncores_separation`.
-   Only use `ncores_separation` for separation step, not all cores.
=> BUG: Number of cores used not matching arguments given

examples/datahandler_custom.py, fissa/core.py, fissa/datahandler.py, fissa/datahandler_framebyframe.py
Causing problems in Python 2, where unicode strings aren't instances of `str`.
This can be fixed in Python 2 by checking `isintance(x, basestring)` instead.
However, in Python 3 basestring was removed, so we import it from `past` (which is provided by the `six` package).
There may be a better way of doing this, more in line with Python 3 style guide, but I think this is the way that will be more user-friendly - using basestring, this will work whether the user gives an implicit byte string or unicode string on Python 2/3.
=> BUG: Check whether string by using isinstance of basestring

README.rst
I think this is the correct standard, instead of DOI in capitals and no space. Not 100% sure though, as I see it done a mixture of ways.
=> DOC: Change DOI to doi and add a space after the colon

fissa/tests/test_datahandler_framebyframe.py, requirements-dev.txt
Because scipy have deprecated imsave in favour of the imageio
package.
=> TST+MAINT: Swap from scipy.misc.imsave to imageio.imwrite

.travis.yml
Mark as failure as soon as a required job fails.
Otherwise, mark as success as soon the only remaining jobs are
allowed to fail.
https://blog.travis-ci.com/2013-11-27-fast-finishing-builds
=> CI: Travis allow fast_finish

README.rst
This pull request does not add much to the FISSA repository itself, but it functions to add a reference to our [newly released SimCalc package](https://github.com/rochefort-lab/SimCalc/), which can be be used to generate simulated calcium data.
=> SimCalc release

LICENSE, README.rst
We're using the GPLv3 license in the LICENSE file, but README incorrectly says FISSA is available under GPLv2.
=> DOC: Fix GPL version mentioned in documentation

setup.py
Add a link to both documentation and source code in the metadata which setup.py will write for PyPI. I think this will add links to them on PyPI next time we push a new version.
=> DOC: Add our URLs to setup.py metadata

docs/conf.py
- Change the title of the [API](https://fissa.readthedocs.io/en/stable/source/packages/modules.html) section of the documentation to be API Reference.
- Make conf.py PEP8 compliant, except for one line which can't be altered and now has a noqa flag.
- Make use of the path value in `__meta__.py`, instead of inferring it here.
=> DOC: Retitle API section of docs to be API Reference, and tidy up conf.py

.travis.yml, requirements-dev.txt, requirements.txt
In its latest release, our dependency tifffile dropped support for Python 2.7 and 3.5, and our unit testing dependency imageio dropped support for Python 2.7.
This was causing problems (and breaking our unit tests on Travis) because pip fails when it tries to install the latest version of these dependencies on the old Python versions. When it goes to install them, it sees that the Python version isn't supported but for some reason doesn't go and find an older version of the package which supports that Python version.
To resolve this, we manually introduce maximum version numbers for these dependencies, which are conditional on the Python version being below a certain version, using [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers).
=> REL: Specify conditional maximum tifffile, imageio version requirements

HOWTO_RELEASE.md
To generate python 2.7 wheel, you need to explicitly tell setup.py that the code is universal with the `--universal` flag for `bdist_wheel`. Otherwise you'll make a wheel which only claims to support python 3, when we actually also support python 2.7.
=> Update release documentation

README.rst
- Fix reference to `continuous_integration` directory, which was moved to `.ci`.
- Describe docs directory, and how to build a local copy of the documentation.
- Add note that this is for if you clone the repo, so people don't expect to get this when they pip install it.
=> DOC: Amend folder listing in README.rst

fissa/core.py
Better inter-operating system support.
=> MAINT: Use os.path.join and not str concat slash

fissa/core.py
If separate() is rerun, we need to clear deltaf_result as it
no longer matches the values held in result.
If separation_prep() is rerun, we need to clear the outputs of
separate() and the outputs of calc_deltaf().
This was split out from PR #70.
=> BUG: Wipe the outputs of downstream outputs when upstream outputs change

fissa/core.py
Closes #51.
When implementing that, I also realised there was another bug:
If you run separate() and have your results present in your fissa Experiment object, and run calc_deltaf(), you'll have deltaf for those results. If you then rerun separate you'll have a potentially different matrix in results and your deltaf won't match the new results. So now we clear deltaf when you run separate, so there can't be a mismatch.
Similarly, now when you run separation_prep, we clear your results produced by both separate() and calc_deltaf().
=> BUG: Save deltaf to matlab file

README.rst
In our documentation, we now direct users to do a one line command to run python, telling it to import fissa and print the version number. Instead of the existing method, which is to run python, then run import fissa. This makes the instructions more concise, and allows the user to check their installed version when they are checking it is installed.
=> DOC: Direct users to print fissa.__version__ to check install

README.rst
Adds a badge to the repo showing the total number of downloads fissa has received through pip.
=> DOC: Add download counter badge

README.rst
- Change the PyPI badge URL to link straight to PyPI page instead of (broken) redirect through badge fury's domain.
- Change to using the official PyPI badge image instead of badge fury's image.
=> DOC: Change pypi badge

.ci/test_notebooks.sh, .travis.yml, requirements_plots.txt
Add a minimum panel version on Python 3.5, fixing a problem with the holoviews requirements chain.
This problem is because holoviews requires panel, and panel requires bokeh. Bokeh had a big 2.0.0 release which dropped support for Python 3.5, and panel moved to the new bokeh api in panel 0.9.0 but didn't specify it no longer supported Python 3.5 until panel 0.9.4. This means installations on Python 3.5 try to install panel 0.9.3, and then find the requirement bokeh>=2.0.0 cannot be satisfied. We fix this by enforcing panel<0.9.0 if python<3.6.
Update some CI settings as well, which I changed to debug this problem but were not necessary to resolve it.
=> DEPS: Maximum version of panel needed on Python 3.5

fissa/core.py
This was causing failed tests to hold indefinitely on Python 3.8.
We can't use a context on Python 2.7 though, so that is still handled the old way.
=> BUG: Use a context for multiprocessing on Python 3

.travis.yml, requirements.txt, requirements_first.txt
Tidy up the conda environment settings, but then disable using conda on Travis and just use pip install instead.
Job matrix is changed to always test notebooks on Python < 3.7. We can't test with the notebooks on Python>=3.7, because SIMA doesn't install (no wheel available on PyPI, and it doesn't compile when we try to install it). We also test one OSX build, though this isn't required for the job to succeed because it can take a while to queue for an environment to be available.
I was going to include a job where all the requirements were installed through conda where possible, and pip otherwise, but couldn't get this working.
Also increase the minimum numpy requirement to 1.13, which was necessary for some oldest dependency builds.
=> CI: Update job matrix; install with pip without conda

.travis.yml
We run an extra job on OSX only when pushing to or issuing a PR to a release branch, and require all OSX jobs to pass on a cron or release branch.
=> CI: Require OSX jobs to pass when releasing

fissa/core.py, fissa/datahandler.py, fissa/datahandler_framebyframe.py
These inputs could legitimately be tuples instead of lists. So I'm broadening the checks to just check for instances of collections.Sequence, which catches all types of sequences.
=> Allow non-list sequences to be used as inputs

fissa/core.py
When ncores is 1, there is no need to use multiprocessing, we should default to the no-multiprocessing behaviour. This will run faster because the routine is run in the current process instead of spinning up a new process and having to handle the extra overhead.
=> MAINT: Don't use multiprocessing when ncores is 1

CHANGELOG.rst
Make "Full commit changelog" be the anchor text, and remove "on github".
=> DOC: Change full commit changelog link text

setup.py
... instead of a single string with new lines as deliminators.
This is not necessary, as either is acceptable, but I think having
a list of strings is cleaner.
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies
We also ensure the ['all'] requirement has no repeated entries
by combining all the individual items together into a set.
=> MAINT: Use splitlines so setup.py has requirements as a list of strings

fissa/datahandler.py, fissa/datahandler_framebyframe.py, fissa/tests/test_datahandler.py, fissa/tests/test_datahandler_framebyframe.py
- Change rois2masks to generate a TypeError instead of ValueError when the wrong type of input is given
- Test that errors are raised when the wrong arguments are given
- Also test with polygons which are transposed
=> TST: Test rois2masks unsupported arguments

.travis.yml
We actually do want to require OSX builds to succeed for updates to master, and new tags, etc, so we only allow jobs to fast finish without OSX when they are PRs (and not PRs into release branches).
=> CI: Require OSX success expect on non-release PRs

fissa/readimagejrois.py, requirements.txt
Resolves the issue/error:
```
File "C:\projects\fissa\fissa\readimagejrois.py", line 129, in _getfloat
v = np.int32(_get32())
OverflowError: Python int too large to convert to C long
```
which was seen when trying to run the code on Windows with
AppVeyor, on a freshly compiled from source copy of FISSA instead
of using the pre-compiled version on conda-forge.
This is fixed by using the imagej roi reader from the package
read_roi. However, their implementation only works for Python 3
and not on Python 2.7. Therefore, we use theirs on Python 3 and
our old method on Python 2.7.
=> BUG+RF: Int OverFlow on Windows resolved on Py3, utilising read_roi

CONTRIBUTING.rst
Add a new commit tag, JNB, which pertains to changes to the notebooks.
=> DOC: Add JNB commit tag to contributing guidelines

fissa/core.py
In numpy 1.16, the default behaviour of numpy.load changed to
stop loading files saved with pickle compression by default.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html
This is due to potential security problems.
However, the default numpy.save behaviour is still to save using
pickle. To preserve user experience, we change our behaviour to
allow loading from pickled files.
This is a short-term solution for #85.
=> BUG: Allow loading pickled numpy cache files

CHANGELOG.rst, fissa/__meta__.py
-   **Caution:** This release knowingly exposes a new security vulnerability. In numpy 1.16, the default behaviour of [numpy.load](https://numpy.org/doc/stable/reference/generated/numpy.load.html) changed to stop loading files saved with pickle compression by default, due to potential security problems. However, the default behaviour of [numpy.save](https://numpy.org/doc/stable/reference/generated/numpy.save.html) is still to save with pickling enabled. In order to preserve our user-experience and backward compatibility with existing fissa cache files, we have changed our behaviour to allow numpy to load from pickled files. ([\#111](https://github.com/rochefort-lab/fissa/pull/111))
-   Officially drop support for Python 3.3 and 3.4. Add `python_requires` to package metadata, specifying …
=> REL: Release version 0.7.0

fissa/deltaf.py
Improve edge-case handling by dynamically reducing number of taps in the filter as necessary, and preventing the baseline from going below the actual minimum value in the data (which in practice won't occur with normal inputs, but can occur when the sequence length is very low).
=> Better handling for deltaf applied to very small datasets

fissa/neuropil.py
Instead of generating a new seed at random when we do a retry from a new initial state, we try the next seed sequentially, looping back to 0 at 2**32 (the maximum value for numpy.RandomState).
This means the output is always fixed for a given seed input.
=> BUG: Use stable seeds on retries

.travis.yml, fissa/tests/test_neuropil.py
Tests for neuropil now:
- use subtest contexts
- test running neuropil separation with different parameter sets
- only test the convergence status of the result, and not the exact number of iterations
This fixes a test which was broken when scikit-learn moved from version 0.22.2.post1 to 0.23.0.
=> TST: Change npil tests

.binder/environment.yml, .travis.yml
We now specify the versions for the Binder environment more precisely, so it is less fragile to changes in other repositories.
The conda env used to test the suite2p notebook now exactly matches that in the Binder environment.
This was motivated by suite2p's current release not working (https://github.com/MouseLand/suite2p/issues/324) with the latest version of skimage=0.17.2. In that release, skimage removed its copy of `tifffile` from `skimage.external.tifffile`. We don't want Binder and our CI test suite to break just because the latest version of two third-party packages are incompatible.
=> Use precise versions in Binder env; test notebooks with that env

.travis.yml
Having problems pushing with the python script (installed via pip)
and it seems like the big name python packages (numpy, pytest)
tend to use the bash script instead, which is working for them.
I took this more robust version of the download command from pytest https://github.com/pytest-dev/pytest/blob/864338de71d6b56f0029b8ea8f45581001e2bab1/scripts/report-coverage.sh
=> CI: Push to codecov with bash script, not python script

fissa/neuropil.py
I think this used to be there for deltaf to use, but is now superfluous to requirements. Nothing in the code base calls this function, and it is not intended to be used by users.
=> RF: Remove unused neuropil.lowPassFilter function

README.rst
Add a link to a google scholar page showing papers which cite FISSA.
=> DOC: Add link to papers citing fissa

examples/Basic usage.html, examples/Basic usage.ipynb, fissa/core.py, fissa/tests/test_core.py
The `folder` argument of `fissa.Experiment` is now optional. If it is not supplied, the data is not loaded from a cache, nor is it saved to a cache.
Also add a test to cover new functionality.
Requires #128.
=> ENH: Add option to run without cache

.appveyor.yml
Remove the init section from .appveyor.yml, which is not working reliable with respect to PR jobs.
https://ci.appveyor.com/project/rochefortlab/fissa/builds/33049428
=> CI: Don't dynamically skip jobs on appveyor

.travis.yml
Reduce the number of OSX jobs which are run for new releases - only test python versions baked into the image (Python 2.7.17 and 3.7.5) and the latest version (Python 3.8.2). Installing other Python versions is very slow (resulting in jobs which take 18 mins instead of 4 mins), and not necessary as they are tested on Ubuntu images.
=> CI: Travis don't test Py3.5 on OSX

fissa/readimagejrois.py
Add this now in case read-roi adds an ellipse ROI type in the future.
=> MNT: Capture ellipse roi type as well as freehand subtype

.github/workflows/docs.yaml, .github/workflows/system_info.py, .github/workflows/test-release-candidate.yaml, .github/workflows/test.yaml, docs/conf.py, docs/requirements.txt, fissa/readimagejrois.py
We need to migrate from TravisCI to GitHub Actions because Travis has ended their "free for open source" policy. (GHA is free to use.)
Based on my template at https://github.com/scottclowe/python-template-repo, this PR adds three workflows:
- doc
- tests
- test-release-candidate
Notes:
- The docs workflow ensures the docs can be built.
- The test workflow runs the unit tests on Python 2.7, 3.5, and 3.9 on Linux, and Py 3.9 on Windows. Unlike the Travis workflow, we don't test compatibility with the oldest versions of our dependencies though.
- The test-release-candidate workflow runs a larger range of OS and Python combinations. It also builds and saves wheels. This only runs on new releases and on PRs to release branches.
- As we are testing Windows here, this will make the AppVeyor …
=> CI: Add tests with GitHub Actions

docs/requirements.txt, fissa/__meta__.py
- Because we use apidoc to generate documentation on the fly, we need all of fissa's requirements installed to build the docs. So we add a reference to the main requirements.txt file to the docs/requirements.txt file that is used by the ammaraskar/sphinx-action@master action in our docs GHA workflow.
- Change the metadata to join authors with "and" instead of "&". This fixes a bug with building the docs as a LaTeX pdf file with sphinx.
=> DOC: Fix docs preventing docs from building

README.rst
Follow up from #154.
We must drop Travis support because they only give a small amount of credits out to open source projects now [[1]](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) [[2]](https://blog.travis-ci.com/oss-announcement) [[3]](https://travis-ci.com/plans), hence the move to GitHub Actions.
=> DOC: Change test badge from Travis to GHA

.travis.yml
- Drop OSX tests. Building these is broken at Travis's side, and we test OSX on GHA PRs now.
- Don't test notebooks on oldest deps.  We don't need to deal with our plotting dependency stack breaking with bad requirement specifications. It's okay as long as our oldest deps are valid for the main package.
=> CI: Fix travis build

.appveyor.yml, .travis.yml
We don't need to replicate jobs running on GHA on the other systems.
Now AppVeyor just runs tests on 32 bit Windows, and Travis just checks on the oldest versions of our dependencies, and the Suite2P notebook (which still builds correctly on Travis).
=> CI: Trim down number of jobs running on Travis and AppVeyor

fissa/ROI.py, fissa/core.py, fissa/readimagejrois.py, fissa/roitools.py, fissa/tests/test_datahandler.py, fissa/tests/test_datahandler_framebyframe.py
- Don't need to import builtins.
- Can always assume multiprocessing is available as it has been part of the standard library since Py 2.7.
- Use os.path.join for building path to test data.
=> RF: Tidy up

fissa/core.py
At the moment, `separation_prep` is called every time `separate` is called.
If caching is enabled, that means `experiment.raw` is wiped and overwritten with a fresh version loaded from disc. If it is the same as the current `self.raw` this is a waste of time loading data which is already loaded. If it is not the same, that may be because the user actually wanted to run on the manually set `experiment.raw` data.
If caching is not enabled, this means the user can run `experiment.separation_prep`, then run `experiment.separate` and `experiment.separation_prep` is needlessly completely redone from scratch. Or they can run `experiment.separate` once, change `alpha` and re-run `experiment.separate` and the prep work is also redone.
This PR changes it so `separate` only calls `separation_prep` …
=> BUG: Don't needlessly redo prep

fissa/core.py
Because we make the first of each output type with list comprehension and then copy it with `np.copy()`, that means one output is a list of lists of x and the others are 2d numpy arrays of x.
This PR changes the odd-one-out so it is a numpy array as well.
=> MNT: Use ndarray for all outputs, not list for some

fissa/core.py, fissa/tests/base_test.py, fissa/tests/test_core.py
In #171 preparation was no longer unnecessarily rerun. However, it introduced a new bug where now separation sometimes unnecessarily ran. This fixes that.
=> BUG: Stop always unnecessarily redoing separate

fissa/core.py, fissa/extraction.py, fissa/tests/test_ROI.py
- Change `np.matrix` to `np.array`
- Use `collections.abc` for abstract base classes, instead of the deprecated alias to them on `collections`
=> MNT: Resolve deprecation warnings

README.rst, docs/conf.py, fissa/ROI.py, fissa/core.py, fissa/deltaf.py, fissa/extraction.py, fissa/neuropil.py, fissa/readimagejrois.py, fissa/roitools.py, fissa/tests/generate_downsampled_resources.py, setup.py
- General docstring improvements.
- Fix rendering of markup in compiled documentation (verified locally against the HTML docs). I had to add `:term:` around some of the type entries which weren't getting picked up automatically. There are still some `str` entries which did not get picked up and still wouldn't work with a `:term:` attribute added.
- Fix some intersphinx issues (numpy moved their documentation, which broke that intersphinx link up). However, `PIL.Image` is still not working correctly; I was unable to resolve that.
- A couple of fixes to the name of the variable in the docstring, where it didn't match the name of the variable accepted by the function/method.
- Blacken sample code within docstrings.
- Change copyright year to 2021.
- Add Python 3.9 to our list of Trove …
=> DOC: Docstring and README improvements

fissa/roitools.py, fissa/tests/test_roitools.py
If we remove the original mask from the grown mask after the first expansion step, we can't use it to grow the first diagonals which is problematic because it leaves checkerboard patterned holes in the npil mask. 
This changes the output of FISSA (not conceptually, but in terms of the exact values outputed), making it match the algorithm described in the paper.
This PR was split out from #54.
=> BUG: Allow first diagonal expansion based on initial mask

fissa/extraction.py, fissa/tests/test_extraction.py
When taking the mean of an array of ints, numpy uses float64 for the output.
But when taking the mean of an array of floats, numpy uses the same float precision as the original array.
That leads to the mean being noticably less accurate when taking the mean of TIFFs that are float16 (single precision). We fix this by using float64 for all the means.
This issue wasn't caught by the unit tests before because they were also doing the less accurate rounding to determine the target values.
=> BUG: Inaccurate means for float16 TIFFs

docs/conf.py, requirements_docs.txt
[pydata](https://pydata-sphinx-theme.readthedocs.io/) is the theme developed by pandas and now also used by numpy, scipy, bokeh and jupyter hub.
Since the pydata theme is only available for Python 3.5+, and only working for us with Python 3.6+, we are still using the readthedocs theme when deploying the documentation on Python 2.7 and 3.5.
=> DOC: Change theme to pydata

.github/workflows/gh-pages.yaml
Add an index.html page to the gh-pages deployment which redirects the page https://rochefort-lab.github.io/fissa/ to https://fissa.readthedocs.io/
I think this is useful since people viewing an example notebook at https://rochefort-lab.github.io/fissa/examples/Basic%20usage.html will expect that deleting the tail of the URL will take them back to the documentation they were just on.
The examples will still be served at `https://rochefort-lab.github.io/fissa/examples/<notebook>.(ipynb|html)` without being affected by the re-direction.
=> DOC: Add a redirect from gh-pages base to readthedocs

fissa/core.py, fissa/tests/base_test.py, fissa/tests/test_core.py, fissa/tests/test_roitools.py
Change from saving a list of a few numpy.ndarrays with [numpy.save](https://numpy.org/doc/stable/reference/generated/numpy.save.html), we save several arrays associated with keys using
[numpy.savez_compressed](https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html).
At the same time, we refactor some code to remove a superfluous nesting depth for the main preparation and separation code blocks.
We now save the means into the .npz file, so this is now restored. This resolves the issue (described in PR #169) that running an experiment that loads from cache does not set `experiment.means`.
=> RF+ENH+BUG: Use npz for cache; store means

fissa/core.py, fissa/extraction.py, fissa/tests/base_test.py, fissa/tests/test_core.py, fissa/tests/test_extraction.py
Add a new datahandler, DataHandlerTifffileLazy, which uses tifffile to handle TIFFs but does so in a lazy manner, loading the data frame-by-frame when determining the traces (like DataHandlerPillow).
The advantage over DataHandlerPillow is it can handle more dtypes and shapes in the TIFF files.
This replaces DataHandlerPillow as the lowmemory_mode datahandler.
=> ENH: Lazy tifffile

fissa/tests/test_extraction.py
When we have tests which are common across multiple objects to test, a handy way of doing this is to make multiple subclasses with different setup but the same test methods. When making the parent subclass, we want it to contain a list of all the tests to run and no set up, and not actually get run itself. We can't subclass BaseTestCase directly because then it is a subclass of unittest.TestCase and will automatically be collected by pytest. Our solution is to use multiple inheritance with a Mixin class. However, the previous way of doing this was not quite doing Mixin classes correctly and it wasn't triggering both parent's `__init__` methods. This resolves the situation into a correct Mixin class. c.f. https://stackoverflow.com/a/50465583/1960959
=> RF: Use Mixin class for extraction tests

.github/workflows/test.yaml
PR #193 and #194 only affected the documentation and not the codebase. When the master branch was updated, the test workflow did not trigger because only paths in paths-ignore were updated. This is a problem for our coverage report, which was expecting to see these results but instead only saw Appveyor Windows builds.
We change the test workflow to run on all pushes. I would like to always run on master and skip running the tests on pushes to other branches which don't affect the codebase, but it is not clear to me if this is actually possible using just the github workflow event triggers.
=> CI:GHA: Always run tests, don't skip based on content

fissa/core.py, fissa/roitools.py
AFAIK, initialising a list as the correct length but composed solely of empty strings offers no noticeable speed advantage. A python list is composed of a double-linked list of pointers to objects, and pointers take up very little memory so you don't need to preallocate the memory for the pointers to go in. See [here](https://stackoverflow.com/questions/311775/create-a-list-with-initial-capacity-in-python). More pythonic code is to use a generator or list  comprehensions where-ever possible. Moreover, initialising the list with contents that have the wrong object type makes for confusing code.
Preallocating memory for numpy arrays is very useful because the object is large.
I've changed these inits to be list comprehension and (for now) just an empty list which is appended to.
=> RF: Don't do init as list of strings

fissa/core.py, fissa/tests/test_core.py
When a variable set to ``None`` is saved to an npz file, it gets turned into numpy.ndarray. We now turn `np.array(None)` back into None when loading it, and also don't save None values to the npz files any more.
This was found when trying to save the matfile for results that had been loaded from cache for the functional notebook #169, so I added a unit test to catch this error.
=> BUG: Saving and loading None values

docs/conf.py, fissa/core.py, fissa/neuropil.py, fissa/roitools.py, requirements-docs.txt
- Move parameters from `__init__` to `Experiment` docstring.
- Add Attributes section covering output attributes.
- Change the Sphinx settings to use numpydoc instead of napolean, which generates better attributes sections in particular.
- Change df/f0 to Δf/f<sub>0</sub>.
- Add link to FISSA paper in Experiment docstring
- Add versionadded directive to the new methods introduced in #177.
=> DOC: Improve core docstrings

fissa/core.py
It is better to clear before setting any of the arguments.
=> MNT: Move self.clear to top of init

fissa/core.py, fissa/extraction.py, fissa/tests/test_core.py, fissa/tests/test_extraction.py
So you can see all the details of a fissa.Experiment instance when you print it.
Tests are also added to ensure the str and repr outputs contain the right information, and that `eval(repr(experiment))` produces a new experiment with the same parameters.
=> ENH: Add __repr__ and __str__ methods

fissa/extraction.py, fissa/roitools.py, fissa/tests/test_extraction.py
Following good software development practice, [DRY: Don't repeat yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), this replicated code should be refactored into a common function.
The only thing which differs is how the image shape is determined, and so I have introduced a function which produces that output and sends it to `roitools.rois2masks`. We are still using DataHandler.rois2masks. For the builtin DataHandler classes, this trivially points to `roitools.rois2masks(rois, self.get_image_size(data)`, but others could make "masks" be non-masks if they would like to have a different interface outside of roitools like @swkeemink was saying in #100.
=> RF: Migrate duplicated rois2masks code to function in roitools

fissa/neuropil.py, fissa/tests/test_neuropil.py
- Remove duplicated code by refactoring so we have common logic only once
- By generalising the code, we enable working with arbitrary [sklearn.decomposition](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.decomposition) classes (e.g. [FactorAnalysis](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.FactorAnalysis.html)), though this feature is undocumented.
- Documentation is improved.
@swkeemink Would be great if you could double-check my descriptions of the methodology for normalising the mixing matrix to rank the signals.
=> RF: Refactor neuropil.separate

requirements-docs.txt
The latest documentation was building correctly locally, but was missing a `:` separator between parameters and they values on readthedocs (since #204 was merged, which migrated from napoleon to numpydoc).
It turned out the issue was coming from using numpydoc (with newer themes) that expect a CSS entry which was added to the core stylesheet (basic.css) in Sphinx 2:
```css
.classifier:before {
font-style: normal;
margin: 0.5em;
content: ":";
}
```
Before sphinx 2, the `:` separator was added to the HTML in its own span.
Consequently, newer versions of numpydoc/themes don't add `:` to the HTML because they expect the sphinx CSS to add it. But somewhere the requirements weren't updated to say `sphinx>2`, so you can end up working with sphinx extensions that expect the sphinx 2 style sheet …
=> DOC+BUG: Missing : separator on readthedocs

fissa/core.py, fissa/extraction.py, fissa/tests/test_core.py
Change the pooling helper functions to take keyword arguments instead of a list of arguments. This makes for a much nicer interface. The pooling helper functions are renamed with nicer names.
We can call it with starmap on Python 3, however there is no starmap on (legacy) Python 2, so we add _extract_wrapper and _separate_wrapper on Python 2 which ends up replicating the behaviour we had before.
=> RF: Change pool functions to take keyword arguments

fissa/tests/test_neuropil.py
=> TST:MNT: Ignore ConvergenceWarning when intentionally not converging

fissa/readimagejrois.py
Because we automatically switch it out for a Python 2 compatible version, and the docstring is rendered as if it is for the wrapper parse_roi_file, which supports both python 2 and python 3.
=> DOC: Don't mention Py 3 requirement in _parse_roi_file_py3

CREDITS.rst, fissa/polygons.py, fissa/roitools.py, fissa/tests/test_polygons.py
We only kept functions related to polygons from the SIMA code, so the name doesn't fit what is in the module.
=> API: Rename module ROI -> polygons

fissa/core.py
separate_trials and Experiment now allow the user to change the maximum number of iterations, the maximum number of tries from different seeds, and the error tolerance of the separation algorithm.
This is useful when a user experiences a lot of non-convergence across cells.
This would close #149
=> API: Expose three separation parameters to fissa UI

.github/workflows/test-release-candidate.yaml, .github/workflows/test.yaml, requirements-test.txt
Any unit test that takes 3 minutes (which is as long as it usually takes to run the whole the test suite) gets killed. It is not expected to ever terminate if it takes longer than that. This prevents the CI queue being held up by zombie tests.
=> CI: Timeout tests that run too long

fissa/core.py, fissa/deltaf.py, fissa/neuropil.py, fissa/roitools.py
Put defaults in docstrings.
c.f. https://numpydoc.readthedocs.io/en/latest/format.html#parameters
=> DOC: Add default values to docstrings

fissa/core.py, fissa/neuropil.py
When the function is added in v1.0.0, we don't need to describe its arguments as added in v1.0.0.
=> DOC: Don't need to specify version added for params in unreleased function

fissa/core.py, requirements.txt
Multiprocessing was giving several issues (such as #147). This PR changes it to using joblib instead.
As a bonus, the code is now much more readable, and the same code is used for Python 2 and 3.
For now it's a draft request as there currently is a bug (known from joblib for a while) that stdout from jupyter notebooks only show up in the terminal, not the notebooks themselves. (See https://github.com/ipython/ipykernel/issues/402 and https://github.com/jupyter/notebook/issues/700). 
It can be fixed by using a different backend, but the whole point is to use the standard joblib backend which fixes our issues.
=> ENH: use joblib instead of multiprocessing

.flake8, fissa/core.py, fissa/tests/test_core.py
Change extract func from outputting OrderedDict for raw traces and polys to output a 3d numpy.ndarray and a list respectively.
=> API: Change outputs from extract func

fissa/core.py, fissa/tests/base_test.py, fissa/tests/test_core.py
- Avoid implicit ragged numpy.ndarray creation when comparing shapes.
- Suppress unavoidable warnings about ragged numpy.ndarray when saving matfile.
- Suppress expected division by zero warnings during unit test suite.
=> MNT: Suppress warnings

fissa/core.py, fissa/tests/test_core.py
If the images or raw attributes are changed after initialising the array, the nTrials and nCell properties can become de-synced with the actual number of images and ROIs. c.f. pakanlab@4f136e7
We stop relying on these properties and dynamically get the values from the current size of result/raw/images.
=> BUG: De-synchronisation in shape

examples/Basic usage - Functional.ipynb, examples/Basic usage.ipynb
Add example of changing verbosity to notebooks. Split out from #238.
=> JNB: Add verbosity control example to notebooks

fissa/core.py, fissa/tests/test_core.py
Set Experiment output attributes to `None` when parameters change.
Example 1:
```python
experiment = fissa.Experiment("path/to/images1", "path/to/rois")
experiment.separate()
experiment.images = "path/to/images2"
```
Example 2:
```python
experiment = fissa.Experiment("path/to/images1", "path/to/rois", expansion=1.2)
experiment.separate()
experiment.expansion = 0.8
```
Example 3:
```python
experiment = fissa.Experiment("path/to/images1", "path/to/rois", alpha=0.1)
experiment.separate()
experiment.alpha = 0.05
```
=> ENH: Automatically wipe output properties when parameter attributes change

.pre-commit-config.yaml, examples/Basic usage - Functional.ipynb, examples/Basic usage.ipynb, examples/SIMA example.ipynb
- Specify that notebooks should be blackened targeting python 2.7, and >=3.5.
- Sanity check notebooks with flake8.
- Fix some flake8 errors in the notebooks.
=> JNB+DEV: Updates to nbqa for notebook pre-commit

.github/workflows/docs.yaml
See issue: ammaraskar/sphinx-action#32
=> CI: Remove broken pdf documentation action

requirements-test.txt
It seems that pytest-flake8 v1.1.0 doesn't support python 2.7 but doesn't declare this, so we have to manually tell pip to avoid it.
=> REL: Fix dependency rot of pytest-flake8 for Python 2.7

.github/workflows/test-release-candidate.yaml, .github/workflows/test.yaml, setup.py
Verify we support running on the latest version, Python 3.10.
=> CI: Test on Python 3.10

fissa/neuropil.py, requirements.txt
In version 1.0.0, sklearn deprecated the `alpha` argument to [NMF](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html) in favour of the `alpha_W` and `alpha_H` arguments, which were added in v1.0.0. The deprecation warning declares that `alpha` will be removed in v1.2.0.
We can't simply swap to using `alpha_W` instead of `alpha` because the behaviour is different:
> When using alpha instead of alpha_W and alpha_H, the regularization terms are not scaled by the n_features (resp. n_samples) factors for W (resp. H).
I imagine the new method where the alphas scale against the number of features/samples is better... but we selected `alpha=0.1` without any such scaling and it is not clear to me without running some tests that we should use `alpha_W=alpha_H=0.1`. …
=> MNT: sklearn deprecation of alpha parameter to NMF

fissa/polygons.py
From Shapely 2.0 onward, multipart geometries such as polygons will no longer be iterable and we have to use the geoms attribute instead.
https://shapely.readthedocs.io/en/latest/migration.html#multi-part-geometries-will-no-longer-be-sequences-length-iterable-indexable
=> MNT: Change Shapely polygons to use geoms attribute

fissa/neuropil.py
Follow-up to de882ba in #271, which did not solve the issue.
We need to filter out FutureWarning, not DeprecationWarning.
=> MNT: Prevent deprecation warning about alpha removal in sklearn v1.2

requirements-docs.txt
The removal of jinja2.utils.escape in Jinja2 v3.1.0 breaks nbconvert, which was relying on this deprecated function.
For more details, see issue here: https://github.com/jupyter/nbconvert/issues/1736
=> DOC+BUG: Prevent nbconvert error missing jinja2.utils.escape

README.rst
Point to the HTML copies of the notebooks embedded in the documentation instead of the standalone HTMLs rendered at rochefort-lab.github.io. This will allow us to have consistent notebooks in the documentation, instead of always linking to the bleeding edge copy even in versions of the documentation which are for older versions of the codebase.
=> DOC: Change HTML notebook links to point to docs page

docs/conf.py, requirements-docs.txt
This reverts commit 8ba523705caa97d81461223d152b86fd9c54b61d.
Elastic search is not working with the pydata theme.
=> DOC: Remove elastic search from on readthedocs

HOWTO_RELEASE.md
Need to change the links to point to the tagged version instead of master branch or latest on RTD.
=> DOC: Add a step in release notes to map hard documentation links

.flake8, .github/workflows/gh-pages.yaml, .github/workflows/pre-commit.yaml, .github/workflows/test-release-candidate.yaml, .github/workflows/test.yaml, .pre-commit-config.yaml, docs/conf.py, docs/examples/SIMA example.ipynb, examples/SIMA example.ipynb, fissa/core.py, fissa/extraction.py, fissa/neuropil.py, fissa/readimagejrois.py, fissa/tests/base_test.py, fissa/tests/generate_downsampled_resources.py, fissa/tests/test_core.py, fissa/tests/test_polygons.py, requirements-dev.txt, requirements.txt
- Upgrade outdated tests
- Constrain requirements with upper bounds `numpy>=1.13.0,<1.24` and `shapely>=1.5.17,<2.0` as we do not currently support newer versions of these dependencies. Numpy 1.24 [stopped automatically detecting ragged arrays](https://numpy.org/neps/nep-0034-infer-dtype-is-object.html), which now need to be specified with `dtype=object`. Shapely 2.0 has some backward-incompatible API changes.
Closes #285. Closes #290.
=> Add cap to numpy and shapely version support, fix tests, upgrade precommit

requirements-docs.txt
This bump to the documentation builder versions ~should~ might fix the GHA docs build.
=> DOC+REL: Require more recent sphinx and Jinja2 versions

requirements.txt
See tifffile changelog here: https://github.com/cgohlke/tifffile/blob/f1d053c1f9922a207b84df615eefa52c6fbae3bb/CHANGES.rst#L9
I think imsave was renamed to imwrite, but I'm not 100% sure.
=> REL: Set maximum tifffile version, as 2025.2.18 removed imsave

.readthedocs.yaml
We need to move from having our config set on readthedocs.org to having it set in a .readthedocs.yaml file.
=> DOC: Add .readthedocs.yaml

.github/workflows/gh-pages.yaml
See gh-pages/notebooks action here: https://github.com/rochefort-lab/fissa/actions/runs/13506739558
=> DEV: Drop sima from GHA as it no longer builds

.readthedocs.yaml
Forgot to commit this in #296, so the path to conf.py was wrong.
=> DOC: Correct path to conf.py for readthedocs
