rochefort-lab/fissa

CONTRIBUTING.md

Not sure how this got in there!

DOC: Fix bad link to repo in CONTRIBUTING

---

CREDITS.rst

- Add a title to the page
- Add URLs for things we are using
- Add our citation

DOC: Tidy credits

---

fissa/tests/test_datahandler_framebyframe.py

Adds tests based on those for the other datahandler.

TST: Add some tests for frame-by-frame datahandler

---

fissa/datahandler.py
fissa/datahandler_framebyframe.py
fissa/neuropil.py

Addresses some cases which were not being caught before.

MAINT: tidy up case handling

---

.travis.yml
docs/conf.py

Make the documentation on Travis to continuously check they can be built.

CI: Use Travis to check docs build

---

README.rst

Add doc and coverage badges.
Also, add a link to documentation at readthedocs.

DOC: Add badges

---

CHANGELOG.rst
fissa/__meta__.py

Update the version number to 0.6.0, and update CHANGELOG.

REL: 0.6.0

---

HOWTO_RELEASE.md

The guide is quite comprehensive by this point, with a step-by-step guide on how to release new versions of the code onto github and pypi.

DOC: Add guide on how to release new versions

---

CHANGELOG.rst
fissa/__meta__.py

Update changelog and rotate version number.

REL: Release version 0.6.1

---

CHANGELOG.rst
fissa/__meta__.py

Merge the release details for v0.6.2 into the history of master.

REL: Add release of v0.6.2 to master

---

fissa/roitools.py
fissa/tests/base_test.py
fissa/tests/test_roitools.py

Can separate out into multiple PRs if preferred.

Bug fixes and tests for roitools

---

.travis.yml
requirements-dev.txt
requirements_plots.txt

#110 was slightly wrong - we were including only branches of form 0.1.2 and v0.1.2, and not v0.1.x or 0.x.y. This PR corrects this.

CI: Travis fix osx branch regex to include v0.1.x

---

CHANGELOG.rst
fissa/__meta__.py

Adds new release v0.7.0 to the CHANGELOG.

DOC: Add v0.7.0 to CHANGELOG

---

README.rst

I deleted a step after first drafting the instructions and forgot to change the step numbers to reflect this.

DOC: Fix numbers in list of steps for windows install

---

HOWTO_RELEASE.md

New instructions for how to release new versions of FISSA.
- Has more detail where necessary.
- More executable code-blocks to speed up the process, which use an MNP variable to know what the name of the release is, and hence what the branch will be called, etc.
- The step for setting up the branch protection rule was removed, because I changed the protection rule to automatically to be for all minor release branches (all branches matching pattern `v.*.*.x`).
- The step for activating the release on ReadTheDocs was removed because RTD automatically activates it.

DOC: Update how-to-release instructions

---

fissa/core.py
fissa/tests/test_core.py

Adds the ability to customise the path of the saved matfile.
Also, add a test for the new functionality.

ENH: matfile save path customisation

---

MANIFEST.in

Specify that source documentation files in the root directory need to be included in the wheel release built for PyPI.

REL: Add MANIFEST.in

---

.codecov.yml

Adapted from sklearn's [.codecov.yml](https://github.com/scikit-learn/scikit-learn/blob/617ff6e/.codecov.yml) config file.

CI: Add .codecov.yml to allow small decreases in coverage

---

.appveyor.yml
.github/workflows/test-release-candidate.yaml
.github/workflows/test.yaml

Measure coverage of notebook smoke tests, and send this report to codecov.

CI: Report notebook coverage

---

fissa/tests/test_core.py

Add some tests on matfile contents.

TST: Test matfile output

---

fissa/core.py
fissa/tests/test_core.py

Also add a test for coverage of this.

MNT: Raise an error when both lowmemory mode and manual datahandler are set

---

fissa/core.py

DOC: Add note about deltaf_result baseline

---

fissa/readimagejrois.py

MNT: Fix deprecated np.float

---

fissa/tests/test_core.py

TST: Don't run separate when only testing prep steps

---

fissa/core.py
fissa/neuropil.py
fissa/tests/test_core.py
requirements.txt

With this update we add a verbosity level and progress-bar option.
When calling the Experiment class, you have to option to set the ```verbosity``` as follows:
```
experiment = fissa.Experiment(images_location, rois_location, output_folder, verbosity=1)
```
With verbosity levels ranging from 0 to 3:
0 - No outputs
1 - Progress bars + high level summary
2 - Print intermediate progress steps
3 - Print per-cell progress
This will close issue #155.

ENH: add verbosity settings flow

---

fissa/tests/test_neuropil.py

Check the right outputs are printed when verbose, and are not printed when quiet.

TST: Test neuropil.separate verbosity

---

fissa/core.py
fissa/tests/test_core.py

Previous verbosity level 2 and above are moved up by one to accommodate the new verbosity level 2. Now verbosity levels 1 and 2 both use progress bars and these are only lost at level 3.

ENH: New verbosity=2: argument description and progress bars

---

fissa/tests/base_test.py
fissa/tests/test_core.py

Follow up to #243, which was not sufficient.

MNT: Suppress warnings (again)

---

pyproject.toml

Add a minimal pyproject.toml that specifies to build the package with setuptools.

REL: Add pyproject.toml

---

examples/Suite2p example.ipynb

This is a simple PR that only updates the Suite2p notebook to work with latest Suite2p API changes.
Currently we do not support Suite2p on Binder but this will come in a follow-up update.

JNB:BUG: updated Suite2p notebook for Suite2p API changes

---

README.rst

DOC: Fix URL pointing to function-based notebook

---

.github/workflows/gh-pages.yaml
.github/workflows/test.yaml

Need to upgrade python version for a valid build environment.

CI: Fix running doc bulid test with ghpages action
